ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/auth"
  realm: "ktor sample app"
  secret: "jwt-secret-coffee-shop-api"
  issuer: "http://0.0.0.0:8080/"
